#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
# 加载job
Fwk::Config.instance.modules.each do |m|
  module_path = Fwk::Config.instance.module_path(m)
  if m.eql?("fwk")
    job_path = "#{module_path}/lib/#{m}/sunspot/"
    if File.directory?(job_path)
      Dir.foreach(job_path) do |filename|
        if filename != "." and filename != ".." and !filename.to_s.index("~")
          file_path = "#{job_path}#{filename}"
          if File.exist?(file_path)
            require file_path
          end
        end
      end
    end
  else
    module_path = Fwk::Config.instance.module_path(m)
    job_path = "#{module_path}/lib/"
    if File.directory?(job_path)
      Dir.foreach(job_path) do |filename|
        if filename != "." and filename != ".." and !filename.to_s.index("~") and !filename.to_s.index(".rb")
          new_job_path = "#{job_path}#{filename}/jobs/"
          if File.directory?(new_job_path)
            Dir.foreach(new_job_path) do |file_name|
              if file_name != "." and file_name != ".." and !file_name.to_s.index("~")
                file_path = "#{new_job_path}#{file_name}"
                if File.exist?(file_path)
                  require file_path
                end
              end
            end
          end
        end
      end
    end
  end
end
Delayed::Command.new(ARGV).daemonize